/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.keys


import com.kbalazsworks.ssp_ai_backend.db.tables.Companies
import com.kbalazsworks.ssp_ai_backend.db.tables.FlywaySchemaHistory
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraBoards
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraSprints
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraTicketEmbeddings
import com.kbalazsworks.ssp_ai_backend.db.tables.records.CompaniesRecord
import com.kbalazsworks.ssp_ai_backend.db.tables.records.FlywaySchemaHistoryRecord
import com.kbalazsworks.ssp_ai_backend.db.tables.records.JiraBoardsRecord
import com.kbalazsworks.ssp_ai_backend.db.tables.records.JiraSprintsRecord
import com.kbalazsworks.ssp_ai_backend.db.tables.records.JiraTicketEmbeddingsRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val COMPANIES_PKEY: UniqueKey<CompaniesRecord> = Internal.createUniqueKey(Companies.COMPANIES, DSL.name("companies_pkey"), arrayOf(Companies.COMPANIES.ID), true)
val FLYWAY_SCHEMA_HISTORY_PK: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
val JIRA_BOARDS_PKEY: UniqueKey<JiraBoardsRecord> = Internal.createUniqueKey(JiraBoards.JIRA_BOARDS, DSL.name("jira_boards_pkey"), arrayOf(JiraBoards.JIRA_BOARDS.ID), true)
val JIRA_SPRINTS_PKEY: UniqueKey<JiraSprintsRecord> = Internal.createUniqueKey(JiraSprints.JIRA_SPRINTS, DSL.name("jira_sprints_pkey"), arrayOf(JiraSprints.JIRA_SPRINTS.ID), true)
val JIRA_TICKET_EMBEDDINGS_PKEY: UniqueKey<JiraTicketEmbeddingsRecord> = Internal.createUniqueKey(JiraTicketEmbeddings.JIRA_TICKET_EMBEDDINGS, DSL.name("jira_ticket_embeddings_pkey"), arrayOf(JiraTicketEmbeddings.JIRA_TICKET_EMBEDDINGS.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val JIRA_BOARDS__JIRA_BOARDS_COMPANY_ID_FKEY: ForeignKey<JiraBoardsRecord, CompaniesRecord> = Internal.createForeignKey(JiraBoards.JIRA_BOARDS, DSL.name("jira_boards_company_id_fkey"), arrayOf(JiraBoards.JIRA_BOARDS.COMPANY_ID), com.kbalazsworks.ssp_ai_backend.db.keys.COMPANIES_PKEY, arrayOf(Companies.COMPANIES.ID), true)
val JIRA_SPRINTS__JIRA_SPRINTS_JIRA_BOARD_ID_FKEY: ForeignKey<JiraSprintsRecord, JiraBoardsRecord> = Internal.createForeignKey(JiraSprints.JIRA_SPRINTS, DSL.name("jira_sprints_jira_board_id_fkey"), arrayOf(JiraSprints.JIRA_SPRINTS.JIRA_BOARD_ID), com.kbalazsworks.ssp_ai_backend.db.keys.JIRA_BOARDS_PKEY, arrayOf(JiraBoards.JIRA_BOARDS.ID), true)
val JIRA_TICKET_EMBEDDINGS__JIRA_TICKET_EMBEDDINGS_JIRA_SPRINT_ID_FKEY: ForeignKey<JiraTicketEmbeddingsRecord, JiraSprintsRecord> = Internal.createForeignKey(JiraTicketEmbeddings.JIRA_TICKET_EMBEDDINGS, DSL.name("jira_ticket_embeddings_jira_sprint_id_fkey"), arrayOf(JiraTicketEmbeddings.JIRA_TICKET_EMBEDDINGS.JIRA_SPRINT_ID), com.kbalazsworks.ssp_ai_backend.db.keys.JIRA_SPRINTS_PKEY, arrayOf(JiraSprints.JIRA_SPRINTS.ID), true)
