/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db


import com.kbalazsworks.ssp_ai_backend.db.tables.Companies
import com.kbalazsworks.ssp_ai_backend.db.tables.FlywaySchemaHistory
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraBoards
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraSprints
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraTicketEmbeddings

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.companies</code>.
     */
    val COMPANIES: Companies get() = Companies.COMPANIES

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory get() = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

    /**
     * The table <code>public.jira_boards</code>.
     */
    val JIRA_BOARDS: JiraBoards get() = JiraBoards.JIRA_BOARDS

    /**
     * The table <code>public.jira_sprints</code>.
     */
    val JIRA_SPRINTS: JiraSprints get() = JiraSprints.JIRA_SPRINTS

    /**
     * The table <code>public.jira_ticket_embeddings</code>.
     */
    val JIRA_TICKET_EMBEDDINGS: JiraTicketEmbeddings get() = JiraTicketEmbeddings.JIRA_TICKET_EMBEDDINGS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Companies.COMPANIES,
        FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
        JiraBoards.JIRA_BOARDS,
        JiraSprints.JIRA_SPRINTS,
        JiraTicketEmbeddings.JIRA_TICKET_EMBEDDINGS
    )
}
