/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.tables


import com.kbalazsworks.ssp_ai_backend.db.Public
import com.kbalazsworks.ssp_ai_backend.db.keys.COMPANIES_PKEY
import com.kbalazsworks.ssp_ai_backend.db.keys.JIRA_BOARDS__JIRA_BOARDS_COMPANY_ID_FKEY
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraBoards.JiraBoardsPath
import com.kbalazsworks.ssp_ai_backend.db.tables.records.CompaniesRecord

import java.time.LocalDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Companies(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CompaniesRecord>?,
    parentPath: InverseForeignKey<out Record, CompaniesRecord>?,
    aliased: Table<CompaniesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CompaniesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.companies</code>
         */
        val COMPANIES: Companies = Companies()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CompaniesRecord> = CompaniesRecord::class.java

    /**
     * The column <code>public.companies.id</code>.
     */
    val ID: TableField<CompaniesRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.companies.name</code>.
     */
    val NAME: TableField<CompaniesRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.companies.created_at</code>.
     */
    val CREATED_AT: TableField<CompaniesRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<CompaniesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CompaniesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CompaniesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.companies</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.companies</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.companies</code> table reference
     */
    constructor(): this(DSL.name("companies"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CompaniesRecord>?, parentPath: InverseForeignKey<out Record, CompaniesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, COMPANIES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CompaniesPath : Companies, Path<CompaniesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CompaniesRecord>?, parentPath: InverseForeignKey<out Record, CompaniesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CompaniesRecord>): super(alias, aliased)
        override fun `as`(alias: String): CompaniesPath = CompaniesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CompaniesPath = CompaniesPath(alias, this)
        override fun `as`(alias: Table<*>): CompaniesPath = CompaniesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<CompaniesRecord, Long?> = super.getIdentity() as Identity<CompaniesRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<CompaniesRecord> = COMPANIES_PKEY

    private lateinit var _jiraBoards: JiraBoardsPath

    /**
     * Get the implicit to-many join path to the <code>public.jira_boards</code>
     * table
     */
    fun jiraBoards(): JiraBoardsPath {
        if (!this::_jiraBoards.isInitialized)
            _jiraBoards = JiraBoardsPath(this, null, JIRA_BOARDS__JIRA_BOARDS_COMPANY_ID_FKEY.inverseKey)

        return _jiraBoards;
    }

    val jiraBoards: JiraBoardsPath
        get(): JiraBoardsPath = jiraBoards()
    override fun `as`(alias: String): Companies = Companies(DSL.name(alias), this)
    override fun `as`(alias: Name): Companies = Companies(alias, this)
    override fun `as`(alias: Table<*>): Companies = Companies(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Companies = Companies(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Companies = Companies(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Companies = Companies(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Companies = Companies(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Companies = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Companies = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Companies = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Companies = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Companies = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Companies = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Companies = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Companies = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Companies = where(DSL.notExists(select))
}
