/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.tables


import com.kbalazsworks.ssp_ai_backend.db.Public
import com.kbalazsworks.ssp_ai_backend.db.keys.JIRA_BOARDS_PKEY
import com.kbalazsworks.ssp_ai_backend.db.keys.JIRA_BOARDS__JIRA_BOARDS_COMPANY_ID_FKEY
import com.kbalazsworks.ssp_ai_backend.db.keys.JIRA_SPRINTS__JIRA_SPRINTS_JIRA_BOARD_ID_FKEY
import com.kbalazsworks.ssp_ai_backend.db.tables.Companies.CompaniesPath
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraSprints.JiraSprintsPath
import com.kbalazsworks.ssp_ai_backend.db.tables.records.JiraBoardsRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JiraBoards(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JiraBoardsRecord>?,
    parentPath: InverseForeignKey<out Record, JiraBoardsRecord>?,
    aliased: Table<JiraBoardsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JiraBoardsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.jira_boards</code>
         */
        val JIRA_BOARDS: JiraBoards = JiraBoards()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JiraBoardsRecord> = JiraBoardsRecord::class.java

    /**
     * The column <code>public.jira_boards.id</code>.
     */
    val ID: TableField<JiraBoardsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.jira_boards.company_id</code>.
     */
    val COMPANY_ID: TableField<JiraBoardsRecord, Long?> = createField(DSL.name("company_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.jira_boards.name</code>.
     */
    val NAME: TableField<JiraBoardsRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.jira_boards.created_at</code>.
     */
    val CREATED_AT: TableField<JiraBoardsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JiraBoardsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JiraBoardsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JiraBoardsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.jira_boards</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.jira_boards</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.jira_boards</code> table reference
     */
    constructor(): this(DSL.name("jira_boards"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, JiraBoardsRecord>?, parentPath: InverseForeignKey<out Record, JiraBoardsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, JIRA_BOARDS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class JiraBoardsPath : JiraBoards, Path<JiraBoardsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, JiraBoardsRecord>?, parentPath: InverseForeignKey<out Record, JiraBoardsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<JiraBoardsRecord>): super(alias, aliased)
        override fun `as`(alias: String): JiraBoardsPath = JiraBoardsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): JiraBoardsPath = JiraBoardsPath(alias, this)
        override fun `as`(alias: Table<*>): JiraBoardsPath = JiraBoardsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<JiraBoardsRecord, Long?> = super.getIdentity() as Identity<JiraBoardsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<JiraBoardsRecord> = JIRA_BOARDS_PKEY
    override fun getReferences(): List<ForeignKey<JiraBoardsRecord, *>> = listOf(JIRA_BOARDS__JIRA_BOARDS_COMPANY_ID_FKEY)

    private lateinit var _companies: CompaniesPath

    /**
     * Get the implicit join path to the <code>public.companies</code> table.
     */
    fun companies(): CompaniesPath {
        if (!this::_companies.isInitialized)
            _companies = CompaniesPath(this, JIRA_BOARDS__JIRA_BOARDS_COMPANY_ID_FKEY, null)

        return _companies;
    }

    val companies: CompaniesPath
        get(): CompaniesPath = companies()

    private lateinit var _jiraSprints: JiraSprintsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.jira_sprints</code> table
     */
    fun jiraSprints(): JiraSprintsPath {
        if (!this::_jiraSprints.isInitialized)
            _jiraSprints = JiraSprintsPath(this, null, JIRA_SPRINTS__JIRA_SPRINTS_JIRA_BOARD_ID_FKEY.inverseKey)

        return _jiraSprints;
    }

    val jiraSprints: JiraSprintsPath
        get(): JiraSprintsPath = jiraSprints()
    override fun `as`(alias: String): JiraBoards = JiraBoards(DSL.name(alias), this)
    override fun `as`(alias: Name): JiraBoards = JiraBoards(alias, this)
    override fun `as`(alias: Table<*>): JiraBoards = JiraBoards(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JiraBoards = JiraBoards(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JiraBoards = JiraBoards(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JiraBoards = JiraBoards(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JiraBoards = JiraBoards(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JiraBoards = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JiraBoards = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JiraBoards = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JiraBoards = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JiraBoards = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JiraBoards = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JiraBoards = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JiraBoards = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JiraBoards = where(DSL.notExists(select))
}
