/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.tables


import com.kbalazsworks.ssp_ai_backend.db.Public
import com.kbalazsworks.ssp_ai_backend.db.keys.JIRA_ISSUES_PKEY
import com.kbalazsworks.ssp_ai_backend.db.keys.JIRA_ISSUES__JIRA_ISSUES_JIRA_SPRINT_ID_FKEY
import com.kbalazsworks.ssp_ai_backend.db.keys.VECTOR_STORE_1536__VECTOR_STORE_1536_JIRA_ISSUE_ID_FKEY
import com.kbalazsworks.ssp_ai_backend.db.keys.VECTOR_STORE_3072__VECTOR_STORE_3072_JIRA_ISSUE_ID_FKEY
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraSprints.JiraSprintsPath
import com.kbalazsworks.ssp_ai_backend.db.tables.VectorStore_1536.VectorStore_1536Path
import com.kbalazsworks.ssp_ai_backend.db.tables.VectorStore_3072.VectorStore_3072Path
import com.kbalazsworks.ssp_ai_backend.db.tables.records.JiraIssuesRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JiraIssues(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JiraIssuesRecord>?,
    parentPath: InverseForeignKey<out Record, JiraIssuesRecord>?,
    aliased: Table<JiraIssuesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JiraIssuesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.jira_issues</code>
         */
        val JIRA_ISSUES: JiraIssues = JiraIssues()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JiraIssuesRecord> = JiraIssuesRecord::class.java

    /**
     * The column <code>public.jira_issues.id</code>.
     */
    val ID: TableField<JiraIssuesRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.jira_issues.jira_sprint_id</code>.
     */
    val JIRA_SPRINT_ID: TableField<JiraIssuesRecord, Long?> = createField(DSL.name("jira_sprint_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.jira_issues.raw_json</code>.
     */
    val RAW_JSON: TableField<JiraIssuesRecord, String?> = createField(DSL.name("raw_json"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.jira_issues.openai_compatible_text</code>.
     */
    val OPENAI_COMPATIBLE_TEXT: TableField<JiraIssuesRecord, String?> = createField(DSL.name("openai_compatible_text"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.jira_issues.created_at</code>.
     */
    val CREATED_AT: TableField<JiraIssuesRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JiraIssuesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JiraIssuesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JiraIssuesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.jira_issues</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.jira_issues</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.jira_issues</code> table reference
     */
    constructor(): this(DSL.name("jira_issues"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, JiraIssuesRecord>?, parentPath: InverseForeignKey<out Record, JiraIssuesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, JIRA_ISSUES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class JiraIssuesPath : JiraIssues, Path<JiraIssuesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, JiraIssuesRecord>?, parentPath: InverseForeignKey<out Record, JiraIssuesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<JiraIssuesRecord>): super(alias, aliased)
        override fun `as`(alias: String): JiraIssuesPath = JiraIssuesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): JiraIssuesPath = JiraIssuesPath(alias, this)
        override fun `as`(alias: Table<*>): JiraIssuesPath = JiraIssuesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<JiraIssuesRecord, Long?> = super.getIdentity() as Identity<JiraIssuesRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<JiraIssuesRecord> = JIRA_ISSUES_PKEY
    override fun getReferences(): List<ForeignKey<JiraIssuesRecord, *>> = listOf(JIRA_ISSUES__JIRA_ISSUES_JIRA_SPRINT_ID_FKEY)

    private lateinit var _jiraSprints: JiraSprintsPath

    /**
     * Get the implicit join path to the <code>public.jira_sprints</code> table.
     */
    fun jiraSprints(): JiraSprintsPath {
        if (!this::_jiraSprints.isInitialized)
            _jiraSprints = JiraSprintsPath(this, JIRA_ISSUES__JIRA_ISSUES_JIRA_SPRINT_ID_FKEY, null)

        return _jiraSprints;
    }

    val jiraSprints: JiraSprintsPath
        get(): JiraSprintsPath = jiraSprints()

    private lateinit var _vectorStore_1536: VectorStore_1536Path

    /**
     * Get the implicit to-many join path to the
     * <code>public.vector_store_1536</code> table
     */
    fun vectorStore_1536(): VectorStore_1536Path {
        if (!this::_vectorStore_1536.isInitialized)
            _vectorStore_1536 = VectorStore_1536Path(this, null, VECTOR_STORE_1536__VECTOR_STORE_1536_JIRA_ISSUE_ID_FKEY.inverseKey)

        return _vectorStore_1536;
    }

    val vectorStore_1536: VectorStore_1536Path
        get(): VectorStore_1536Path = vectorStore_1536()

    private lateinit var _vectorStore_3072: VectorStore_3072Path

    /**
     * Get the implicit to-many join path to the
     * <code>public.vector_store_3072</code> table
     */
    fun vectorStore_3072(): VectorStore_3072Path {
        if (!this::_vectorStore_3072.isInitialized)
            _vectorStore_3072 = VectorStore_3072Path(this, null, VECTOR_STORE_3072__VECTOR_STORE_3072_JIRA_ISSUE_ID_FKEY.inverseKey)

        return _vectorStore_3072;
    }

    val vectorStore_3072: VectorStore_3072Path
        get(): VectorStore_3072Path = vectorStore_3072()
    override fun `as`(alias: String): JiraIssues = JiraIssues(DSL.name(alias), this)
    override fun `as`(alias: Name): JiraIssues = JiraIssues(alias, this)
    override fun `as`(alias: Table<*>): JiraIssues = JiraIssues(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JiraIssues = JiraIssues(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JiraIssues = JiraIssues(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JiraIssues = JiraIssues(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JiraIssues = JiraIssues(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JiraIssues = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JiraIssues = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JiraIssues = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JiraIssues = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JiraIssues = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JiraIssues = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JiraIssues = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JiraIssues = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JiraIssues = where(DSL.notExists(select))
}
