/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.tables


import com.kbalazsworks.ssp_ai_backend.common.binder.PgVectorBinding
import com.kbalazsworks.ssp_ai_backend.db.Public
import com.kbalazsworks.ssp_ai_backend.db.keys.JIRA_TICKET_EMBEDDINGS_PKEY
import com.kbalazsworks.ssp_ai_backend.db.keys.JIRA_TICKET_EMBEDDINGS__JIRA_TICKET_EMBEDDINGS_JIRA_SPRINT_ID_FKEY
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraSprints.JiraSprintsPath
import com.kbalazsworks.ssp_ai_backend.db.tables.records.JiraTicketEmbeddingsRecord
import com.pgvector.PGvector

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JiraTicketEmbeddings(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JiraTicketEmbeddingsRecord>?,
    parentPath: InverseForeignKey<out Record, JiraTicketEmbeddingsRecord>?,
    aliased: Table<JiraTicketEmbeddingsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JiraTicketEmbeddingsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.jira_ticket_embeddings</code>
         */
        val JIRA_TICKET_EMBEDDINGS: JiraTicketEmbeddings = JiraTicketEmbeddings()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JiraTicketEmbeddingsRecord> = JiraTicketEmbeddingsRecord::class.java

    /**
     * The column <code>public.jira_ticket_embeddings.id</code>.
     */
    val ID: TableField<JiraTicketEmbeddingsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.jira_ticket_embeddings.jira_sprint_id</code>.
     */
    val JIRA_SPRINT_ID: TableField<JiraTicketEmbeddingsRecord, Long?> = createField(DSL.name("jira_sprint_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.jira_ticket_embeddings.raw_json</code>.
     */
    val RAW_JSON: TableField<JiraTicketEmbeddingsRecord, String?> = createField(DSL.name("raw_json"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.jira_ticket_embeddings.embedding1536</code>.
     */
    val EMBEDDING1536: TableField<JiraTicketEmbeddingsRecord, PGvector?> = createField(DSL.name("embedding1536"), DefaultDataType.getDefaultDataType("\"public\".\"vector\""), this, "", PgVectorBinding())

    /**
     * The column <code>public.jira_ticket_embeddings.embedding3072</code>.
     */
    val EMBEDDING3072: TableField<JiraTicketEmbeddingsRecord, PGvector?> = createField(DSL.name("embedding3072"), DefaultDataType.getDefaultDataType("\"public\".\"vector\""), this, "", PgVectorBinding())

    /**
     * The column <code>public.jira_ticket_embeddings.created_at</code>.
     */
    val CREATED_AT: TableField<JiraTicketEmbeddingsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<JiraTicketEmbeddingsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JiraTicketEmbeddingsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JiraTicketEmbeddingsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.jira_ticket_embeddings</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.jira_ticket_embeddings</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.jira_ticket_embeddings</code> table reference
     */
    constructor(): this(DSL.name("jira_ticket_embeddings"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, JiraTicketEmbeddingsRecord>?, parentPath: InverseForeignKey<out Record, JiraTicketEmbeddingsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, JIRA_TICKET_EMBEDDINGS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class JiraTicketEmbeddingsPath : JiraTicketEmbeddings, Path<JiraTicketEmbeddingsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, JiraTicketEmbeddingsRecord>?, parentPath: InverseForeignKey<out Record, JiraTicketEmbeddingsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<JiraTicketEmbeddingsRecord>): super(alias, aliased)
        override fun `as`(alias: String): JiraTicketEmbeddingsPath = JiraTicketEmbeddingsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): JiraTicketEmbeddingsPath = JiraTicketEmbeddingsPath(alias, this)
        override fun `as`(alias: Table<*>): JiraTicketEmbeddingsPath = JiraTicketEmbeddingsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<JiraTicketEmbeddingsRecord, Long?> = super.getIdentity() as Identity<JiraTicketEmbeddingsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<JiraTicketEmbeddingsRecord> = JIRA_TICKET_EMBEDDINGS_PKEY
    override fun getReferences(): List<ForeignKey<JiraTicketEmbeddingsRecord, *>> = listOf(JIRA_TICKET_EMBEDDINGS__JIRA_TICKET_EMBEDDINGS_JIRA_SPRINT_ID_FKEY)

    private lateinit var _jiraSprints: JiraSprintsPath

    /**
     * Get the implicit join path to the <code>public.jira_sprints</code> table.
     */
    fun jiraSprints(): JiraSprintsPath {
        if (!this::_jiraSprints.isInitialized)
            _jiraSprints = JiraSprintsPath(this, JIRA_TICKET_EMBEDDINGS__JIRA_TICKET_EMBEDDINGS_JIRA_SPRINT_ID_FKEY, null)

        return _jiraSprints;
    }

    val jiraSprints: JiraSprintsPath
        get(): JiraSprintsPath = jiraSprints()
    override fun `as`(alias: String): JiraTicketEmbeddings = JiraTicketEmbeddings(DSL.name(alias), this)
    override fun `as`(alias: Name): JiraTicketEmbeddings = JiraTicketEmbeddings(alias, this)
    override fun `as`(alias: Table<*>): JiraTicketEmbeddings = JiraTicketEmbeddings(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JiraTicketEmbeddings = JiraTicketEmbeddings(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JiraTicketEmbeddings = JiraTicketEmbeddings(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JiraTicketEmbeddings = JiraTicketEmbeddings(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JiraTicketEmbeddings = JiraTicketEmbeddings(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JiraTicketEmbeddings = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JiraTicketEmbeddings = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JiraTicketEmbeddings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JiraTicketEmbeddings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JiraTicketEmbeddings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JiraTicketEmbeddings = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JiraTicketEmbeddings = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JiraTicketEmbeddings = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JiraTicketEmbeddings = where(DSL.notExists(select))
}
