/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.tables


import com.kbalazsworks.ssp_ai_backend.common.binder.PgVectorBinding
import com.kbalazsworks.ssp_ai_backend.db.Public
import com.kbalazsworks.ssp_ai_backend.db.keys.QUESTIONS_PKEY
import com.kbalazsworks.ssp_ai_backend.db.tables.records.QuestionsRecord
import com.pgvector.PGvector

import java.time.LocalDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.DefaultDataType
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Questions(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, QuestionsRecord>?,
    parentPath: InverseForeignKey<out Record, QuestionsRecord>?,
    aliased: Table<QuestionsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<QuestionsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.questions</code>
         */
        val QUESTIONS: Questions = Questions()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<QuestionsRecord> = QuestionsRecord::class.java

    /**
     * The column <code>public.questions.id</code>.
     */
    val ID: TableField<QuestionsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.questions.question</code>.
     */
    val QUESTION: TableField<QuestionsRecord, String?> = createField(DSL.name("question"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.questions.embedding1536</code>.
     */
    val EMBEDDING1536: TableField<QuestionsRecord, PGvector?> = createField(DSL.name("embedding1536"), DefaultDataType.getDefaultDataType("\"public\".\"vector\""), this, "", PgVectorBinding())

    /**
     * The column <code>public.questions.embedding3072</code>.
     */
    val EMBEDDING3072: TableField<QuestionsRecord, PGvector?> = createField(DSL.name("embedding3072"), DefaultDataType.getDefaultDataType("\"public\".\"vector\""), this, "", PgVectorBinding())

    /**
     * The column <code>public.questions.created_at</code>.
     */
    val CREATED_AT: TableField<QuestionsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<QuestionsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<QuestionsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<QuestionsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.questions</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.questions</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.questions</code> table reference
     */
    constructor(): this(DSL.name("questions"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<QuestionsRecord, Long?> = super.getIdentity() as Identity<QuestionsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<QuestionsRecord> = QUESTIONS_PKEY
    override fun `as`(alias: String): Questions = Questions(DSL.name(alias), this)
    override fun `as`(alias: Name): Questions = Questions(alias, this)
    override fun `as`(alias: Table<*>): Questions = Questions(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Questions = Questions(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Questions = Questions(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Questions = Questions(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Questions = Questions(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Questions = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Questions = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Questions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Questions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Questions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Questions = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Questions = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Questions = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Questions = where(DSL.notExists(select))
}
