/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.tables


import com.kbalazsworks.ssp_ai_backend.db.Public
import com.kbalazsworks.ssp_ai_backend.db.keys.VECTOR_MODELS_PKEY
import com.kbalazsworks.ssp_ai_backend.db.keys.VECTOR_STORE_1536__VECTOR_STORE_1536_VECTOR_MODEL_ID_FKEY
import com.kbalazsworks.ssp_ai_backend.db.keys.VECTOR_STORE_3072__VECTOR_STORE_3072_VECTOR_MODEL_ID_FKEY
import com.kbalazsworks.ssp_ai_backend.db.tables.VectorStore_1536.VectorStore_1536Path
import com.kbalazsworks.ssp_ai_backend.db.tables.VectorStore_3072.VectorStore_3072Path
import com.kbalazsworks.ssp_ai_backend.db.tables.records.VectorModelsRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VectorModels(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VectorModelsRecord>?,
    parentPath: InverseForeignKey<out Record, VectorModelsRecord>?,
    aliased: Table<VectorModelsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VectorModelsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.vector_models</code>
         */
        val VECTOR_MODELS: VectorModels = VectorModels()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VectorModelsRecord> = VectorModelsRecord::class.java

    /**
     * The column <code>public.vector_models.id</code>.
     */
    val ID: TableField<VectorModelsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.vector_models.name</code>.
     */
    val NAME: TableField<VectorModelsRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<VectorModelsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VectorModelsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VectorModelsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.vector_models</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.vector_models</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.vector_models</code> table reference
     */
    constructor(): this(DSL.name("vector_models"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VectorModelsRecord>?, parentPath: InverseForeignKey<out Record, VectorModelsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, VECTOR_MODELS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class VectorModelsPath : VectorModels, Path<VectorModelsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, VectorModelsRecord>?, parentPath: InverseForeignKey<out Record, VectorModelsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<VectorModelsRecord>): super(alias, aliased)
        override fun `as`(alias: String): VectorModelsPath = VectorModelsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): VectorModelsPath = VectorModelsPath(alias, this)
        override fun `as`(alias: Table<*>): VectorModelsPath = VectorModelsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<VectorModelsRecord, Long?> = super.getIdentity() as Identity<VectorModelsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<VectorModelsRecord> = VECTOR_MODELS_PKEY

    private lateinit var _vectorStore_1536: VectorStore_1536Path

    /**
     * Get the implicit to-many join path to the
     * <code>public.vector_store_1536</code> table
     */
    fun vectorStore_1536(): VectorStore_1536Path {
        if (!this::_vectorStore_1536.isInitialized)
            _vectorStore_1536 = VectorStore_1536Path(this, null, VECTOR_STORE_1536__VECTOR_STORE_1536_VECTOR_MODEL_ID_FKEY.inverseKey)

        return _vectorStore_1536;
    }

    val vectorStore_1536: VectorStore_1536Path
        get(): VectorStore_1536Path = vectorStore_1536()

    private lateinit var _vectorStore_3072: VectorStore_3072Path

    /**
     * Get the implicit to-many join path to the
     * <code>public.vector_store_3072</code> table
     */
    fun vectorStore_3072(): VectorStore_3072Path {
        if (!this::_vectorStore_3072.isInitialized)
            _vectorStore_3072 = VectorStore_3072Path(this, null, VECTOR_STORE_3072__VECTOR_STORE_3072_VECTOR_MODEL_ID_FKEY.inverseKey)

        return _vectorStore_3072;
    }

    val vectorStore_3072: VectorStore_3072Path
        get(): VectorStore_3072Path = vectorStore_3072()
    override fun `as`(alias: String): VectorModels = VectorModels(DSL.name(alias), this)
    override fun `as`(alias: Name): VectorModels = VectorModels(alias, this)
    override fun `as`(alias: Table<*>): VectorModels = VectorModels(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): VectorModels = VectorModels(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): VectorModels = VectorModels(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): VectorModels = VectorModels(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): VectorModels = VectorModels(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): VectorModels = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): VectorModels = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): VectorModels = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): VectorModels = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): VectorModels = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): VectorModels = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): VectorModels = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): VectorModels = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): VectorModels = where(DSL.notExists(select))
}
