# curl -X GET http://localhost:3040/api/v1/ask-ai -H "Content-Type: application/json" -H "Accept: application/json" -d '{"questionId":1,"jiraSprintId":1}'
GET http://localhost:3040/api/v1/ask-ai
Accept: application/json
Content-Type: application/json

{
  "questionId": 1,
  "jiraSprintId": 1
}
