/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.tables.references


import com.kbalazsworks.ssp_ai_backend.db.tables.Companies
import com.kbalazsworks.ssp_ai_backend.db.tables.FlywaySchemaHistory
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraBoards
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraSprints
import com.kbalazsworks.ssp_ai_backend.db.tables.JiraTicketEmbeddings



/**
 * The table <code>public.companies</code>.
 */
val COMPANIES: Companies = Companies.COMPANIES

/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.jira_boards</code>.
 */
val JIRA_BOARDS: JiraBoards = JiraBoards.JIRA_BOARDS

/**
 * The table <code>public.jira_sprints</code>.
 */
val JIRA_SPRINTS: JiraSprints = JiraSprints.JIRA_SPRINTS

/**
 * The table <code>public.jira_ticket_embeddings</code>.
 */
val JIRA_TICKET_EMBEDDINGS: JiraTicketEmbeddings = JiraTicketEmbeddings.JIRA_TICKET_EMBEDDINGS
