/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.tables.records


import com.kbalazsworks.ssp_ai_backend.db.tables.JiraBoards

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JiraBoardsRecord() : UpdatableRecordImpl<JiraBoardsRecord>(JiraBoards.JIRA_BOARDS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var companyId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised JiraBoardsRecord
     */
    constructor(id: Long? = null, companyId: Long? = null, name: String? = null, createdAt: LocalDateTime? = null): this() {
        this.id = id
        this.companyId = companyId
        this.name = name
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
