/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.tables.records


import com.kbalazsworks.ssp_ai_backend.db.tables.JiraTicketEmbeddings
import com.pgvector.PGvector

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class JiraTicketEmbeddingsRecord() : UpdatableRecordImpl<JiraTicketEmbeddingsRecord>(JiraTicketEmbeddings.JIRA_TICKET_EMBEDDINGS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var jiraSprintId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var rawJson: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var openaiCompatibleText: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var embedding1536: PGvector?
        set(value): Unit = set(4, value)
        get(): PGvector? = get(4) as PGvector?

    open var embedding3072: PGvector?
        set(value): Unit = set(5, value)
        get(): PGvector? = get(5) as PGvector?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised JiraTicketEmbeddingsRecord
     */
    constructor(id: Long? = null, jiraSprintId: Long? = null, rawJson: String? = null, openaiCompatibleText: String? = null, embedding1536: PGvector? = null, embedding3072: PGvector? = null, createdAt: LocalDateTime? = null): this() {
        this.id = id
        this.jiraSprintId = jiraSprintId
        this.rawJson = rawJson
        this.openaiCompatibleText = openaiCompatibleText
        this.embedding1536 = embedding1536
        this.embedding3072 = embedding3072
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
