/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.ssp_ai_backend.db.tables.records


import com.kbalazsworks.ssp_ai_backend.db.tables.VectorStore_1536
import com.pgvector.PGvector

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VectorStore_1536Record() : TableRecordImpl<VectorStore_1536Record>(VectorStore_1536.VECTOR_STORE_1536) {

    open var questionId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var jiraIssueId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var vectorModelId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var embedding: PGvector?
        set(value): Unit = set(3, value)
        get(): PGvector? = get(3) as PGvector?

    /**
     * Create a detached, initialised VectorStore_1536Record
     */
    constructor(questionId: Long? = null, jiraIssueId: Long? = null, vectorModelId: Long? = null, embedding: PGvector? = null): this() {
        this.questionId = questionId
        this.jiraIssueId = jiraIssueId
        this.vectorModelId = vectorModelId
        this.embedding = embedding
        resetChangedOnNotNull()
    }
}
